### ISSUE TITLE
About network speed

### ISSUE THREAD

**Issue by gitHatmos** [spacemeowx2/switch-lan-play#24]
When using Switch Lan Play, I want to know if Pcap or Lan-play is responsible for decreasing network speed

**Comment by spacemeowx2** [comment]
You can have a speed test with a laptop with `10.13.x.x` address.

**Comment by gitHatmos** [comment]
ok,i'll try

**Comment by gitHatmos** [comment]
When using --pmtu the line speed got better. (I learned from tkgstrator)

**Comment by spacemeowx2** [comment]
The reason of terrible performances on Linux(see also: #30) has been found. And can be fixed by this commit https://github.com/spacemeowx2/switch-lan-play/commit/1f58b77c751d17c7d449d84008351a3b1188c2c7.

Related issue: https://github.com/the-tcpdump-group/libpcap/issues/550

But to make sure this change will not influence other platform(e.g Windows and Mac), we need test before merging into master.

**Comment by Hol1mol1** [comment]
Hi,
I have problems with slow connection too but on windows:
selecting the best servers the switch download at 3mbps while my pc downloads at 50mbps.
What should I do?  
Thank you in advance and sorry if I should have started a new issue.

**Comment by spacemeowx2** [comment]
@Hol1mol1 The Internet connection on Switch don't pass the server. lan-play server only handles 10.13.x.y network packets. And 3mbps is enough for 99.9% game to play online. So I think you can ignore it.
